### ISSUE TITLE
With longer strings, positions are often wrong and unsorted 

### ISSUE THREAD

**Issue by skovsboll** [hugopl/fzy#2]
Here's a couple of examples:

```
Failures:

  1) Fzy positions are sorted when double letters later in string
     Failure/Error: Fzy.search("bookmarks", %w(clear_bookmarks)).first.positions.should eq([6, 7, 8, 9, 10, 11, 12, 13, 14])

       Expected: [6, 7, 8, 9, 10, 11, 12, 13, 14]
            got: [6, 8, 8, 13, 10, 11, 12, 13, 14]

     # spec/fzy_spec.cr:138

  2) Fzy positions are sorted when double letters beginning of string
     Failure/Error: Fzy.search("aandom", %w(aandom_baandom)).first.positions.should eq([0, 1, 2, 3, 4, 5])

       Expected: [0, 1, 2, 3, 4, 5]
            got: [9, 1, 10, 3, 12, 5]

     # spec/fzy_spec.cr:142

  3) Fzy positions favors start of match
     Failure/Error: Fzy.search("andom", %w(andom_random)).first.positions.should eq([0, 1, 2, 3, 4])

       Expected: [0, 1, 2, 3, 4]
            got: [0, 8, 2, 10, 4]
```
